// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cloud.World.Shared.Database
{
    public partial class TbFileType
    {
        public int Index { get; set; }
        public string Key { get; set; }
        public string Type { get; set; }
    }
}