// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cloud.World.Shared.Database
{
    public partial class TbLog
    {
        public int Index { get; set; }
        public string Batch { get; set; }
        public string Uid { get; set; }
        public string Ip { get; set; }
        public string Action { get; set; }
        public string Parameter { get; set; }
        public DateTime Ltime { get; set; }

        public virtual TbUser UidNavigation { get; set; }
    }
}