// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cloud.World.Shared.Database
{
    public partial class TbNotice
    {
        public int Index { get; set; }
        public string Msg { get; set; }
        public string Publisher { get; set; }
        public DateTime Ntime { get; set; }

        public virtual TbUser PublisherNavigation { get; set; }
    }
}