// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cloud.World.Shared.Database
{
    public partial class TbSubject
    {
        public TbSubject()
        {
            TbCourseSelection = new HashSet<TbCourseSelection>();
            TbProject = new HashSet<TbProject>();
        }

        public string Sid { get; set; }
        public string Sname { get; set; }
        public DateTime Stime { get; set; }
        public int Sstatus { get; set; }
        public string Publisher { get; set; }

        public virtual TbUser PublisherNavigation { get; set; }
        public virtual ICollection<TbCourseSelection> TbCourseSelection { get; set; }
        public virtual ICollection<TbProject> TbProject { get; set; }
    }
}