// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cloud.World.Shared.Database
{
    public partial class TbUser
    {
        public TbUser()
        {
            TbAnnex = new HashSet<TbAnnex>();
            TbCourseSelection = new HashSet<TbCourseSelection>();
            TbFile = new HashSet<TbFile>();
            TbLog = new HashSet<TbLog>();
            TbNotice = new HashSet<TbNotice>();
            TbProject = new HashSet<TbProject>();
            TbSubject = new HashSet<TbSubject>();
        }

        public string Uid { get; set; }
        public string Name { get; set; }
        public string Cid { get; set; }
        public string Phone { get; set; }
        public string Qq { get; set; }
        public string Type { get; set; }

        public virtual TbClass CidNavigation { get; set; }
        public virtual ICollection<TbAnnex> TbAnnex { get; set; }
        public virtual ICollection<TbCourseSelection> TbCourseSelection { get; set; }
        public virtual ICollection<TbFile> TbFile { get; set; }
        public virtual ICollection<TbLog> TbLog { get; set; }
        public virtual ICollection<TbNotice> TbNotice { get; set; }
        public virtual ICollection<TbProject> TbProject { get; set; }
        public virtual ICollection<TbSubject> TbSubject { get; set; }
    }
}