// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cloud.World.Shared.Database
{
    public partial class VAnnex
    {
        public string Pid { get; set; }
        public string Sid { get; set; }
        public string Pname { get; set; }
        public string Introduction { get; set; }
        public DateTime Deadline { get; set; }
        public int Pstatus { get; set; }
        public DateTime Ptime { get; set; }
        public string ProjectPublisher { get; set; }
        public string Aid { get; set; }
        public string Aname { get; set; }
        public string Atype { get; set; }
        public string Apath { get; set; }
        public int Astatus { get; set; }
        public DateTime Atime { get; set; }
        public string AnnexPublisher { get; set; }
    }
}