// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cloud.World.Shared.Database
{
    public partial class VSubmit
    {
        public string Uid { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Qq { get; set; }
        public string Type { get; set; }
        public string Cid { get; set; }
        public string Fid { get; set; }
        public string Batch { get; set; }
        public string Fname { get; set; }
        public string Ftype { get; set; }
        public DateTime Ftime { get; set; }
        public int Size { get; set; }
        public byte[] Hash { get; set; }
        public string Fpath { get; set; }
        public string Pid { get; set; }
        public string Sid { get; set; }
        public string Pname { get; set; }
        public string Introduction { get; set; }
        public DateTime Deadline { get; set; }
        public int Pstatus { get; set; }
        public DateTime Ptime { get; set; }
        public string ProjectPublisher { get; set; }
    }
}