// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cloud.World.Shared.Database
{
    public partial class VUser
    {
        public string Uid { get; set; }
        public byte[] PassWord { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Qq { get; set; }
        public string Type { get; set; }
        public string Cid { get; set; }
        public string Cname { get; set; }
    }
}