// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cloud.World.Shared.Database
{
    public partial class VWork
    {
        public string Sid { get; set; }
        public string Sname { get; set; }
        public DateTime Stime { get; set; }
        public int Sstatus { get; set; }
        public string SubjectPublisher { get; set; }
        public string Pid { get; set; }
        public string Pname { get; set; }
        public string Introduction { get; set; }
        public DateTime Deadline { get; set; }
        public int Pstatus { get; set; }
        public DateTime Ptime { get; set; }
        public string ProjectPublisher { get; set; }
    }
}