// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cloud.Test.Models
{
    public partial class TbAccount
    {
        public string Uid { get; set; }
        public string Password { get; set; }
    }
}