// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cloud.Test.Models
{
    public partial class TbFile
    {
        public string Fid { get; set; }
        public string Uid { get; set; }
        public string Pid { get; set; }
        public string Batch { get; set; }
        public string Fname { get; set; }
        public string Ftype { get; set; }
        public int Size { get; set; }
        public byte[] Hash { get; set; }
        public DateTime Ftime { get; set; }
        public string Fpath { get; set; }
        public int Fstatus { get; set; }

        public virtual TbProject PidNavigation { get; set; }
        public virtual TbUser UidNavigation { get; set; }
    }
}