// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cloud.Test.Models
{
    public partial class TbLog
    {
        public int Index { get; set; }
        public string Uid { get; set; }
        public string Action { get; set; }
        public string Parameter { get; set; }
        public DateTime LogTime { get; set; }

        public virtual TbUser UidNavigation { get; set; }
    }
}