// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cloud.Test.Models
{
    public partial class TbProject
    {
        public TbProject()
        {
            TbFile = new HashSet<TbFile>();
        }

        public string Pid { get; set; }
        public string Sid { get; set; }
        public string Pname { get; set; }
        public string Introduction { get; set; }
        public string Requirement { get; set; }
        public string RequiredType { get; set; }
        public DateTime Ptime { get; set; }
        public int Pstatus { get; set; }

        public virtual TbSubject SidNavigation { get; set; }
        public virtual ICollection<TbFile> TbFile { get; set; }
    }
}