// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cloud.Test.Models
{
    public partial class TbSubject
    {
        public TbSubject()
        {
            TbProject = new HashSet<TbProject>();
        }

        public string Sid { get; set; }
        public string Sname { get; set; }
        public DateTime Stime { get; set; }
        public int Sstatus { get; set; }

        public virtual ICollection<TbProject> TbProject { get; set; }
    }
}