// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cloud.Test.Models
{
    public partial class TbUser
    {
        public TbUser()
        {
            TbFile = new HashSet<TbFile>();
            TbLog = new HashSet<TbLog>();
        }

        public string Uid { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Phone { get; set; }
        public string Qq { get; set; }

        public virtual ICollection<TbFile> TbFile { get; set; }
        public virtual ICollection<TbLog> TbLog { get; set; }
    }
}